Repository team-dopamine/husk-web, pull requests merged in 2024-12, with the labels that each got.

#9 feature(HK-64): Main 페이지 구현
  src/pages/main/content/index.style.tsx
  src/pages/main/content/index.tsx
  src/pages/main/index.tsx
Labels: enhancement

#10 Fix(HK-68): 메인 페이지 수정
  src/pages/main/content/index.style.tsx
  src/pages/main/content/index.tsx
Labels: bug

#11 Feature(HK-69): 로그인 페이지 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/header/index.style.tsx
  src/components/header/index.tsx
  src/pages/sign-in/content/index.style.tsx
  src/pages/sign-in/content/index.tsx
  src/pages/sign-in/index.style.tsx
  src/pages/sign-in/index.tsx
Labels: enhancement, authorization
