Repository team-dopamine/husk-web, pull requests merged in 2025-05, with the labels that each got.

#56 Feature(HK-145): 웹터미널 구현
  package-lock.json
  package.json
  src/App.tsx
  src/api/socket/index.tsx
  src/components/terminal/index.tsx
  src/pages/ssh-connection/index.tsx
  src/pages/terminal/index.style.tsx
  src/pages/terminal/index.tsx
Labels: enhancement, ssh connection

#57 Fix(HK-149): cd.yml ubuntu 버전 업데이트
  .github/workflows/cd.yml
Labels: bug

#58 Feature(HK-129): SSH 커넥션 저장 API 연동
  src/api/ssh-connections/ssh-register/ssh-connection-register/index.tsx
  src/components/dashboard/button/saveButton/index.tsx
  src/components/dashboard/modals/register-modal/index.tsx
  src/components/dashboard/modals/register-modal/types/index.tsx
  src/pages/keychain/index.tsx
  src/pages/ssh-connection/index.tsx
Labels: enhancement

#59 Refactor(HK-151): SSH 관련 컴포넌트 리팩토링
  src/components/dashboard/cards/sshConnection-card/index.tsx
  src/components/dashboard/modals/sshConnection/index.tsx
  src/pages/ssh-connection/index.tsx
Labels: enhancement, fix

#60 Feature(HK-144): SSH 커넥션 삭제 API 연동
  src/api/ssh-connections/ssh-delete/index.tsx
  src/components/dashboard/cards/sshConnection-card/index.tsx
  src/components/dashboard/modals/register-modal/index.tsx
  src/components/dashboard/modals/register-modal/types/index.tsx
  src/components/dashboard/modals/sshConnection/handlers/index.tsx
  src/components/dashboard/modals/sshConnection/index.tsx
  src/components/dashboard/modals/types/index.tsx
Labels: enhancement, ssh connection

#61 Refactor(HK-140): Keychain 페이지 리팩토링
  src/components/dashboard/cards/keychain-card/index.tsx
  src/pages/keychain/index.tsx
Labels: fix

#63 Feature(HK-155): SSH 커넥션 상세 조회 API 연동
  src/api/ssh-connections/ssh-detail-read/index.tsx
  src/api/ssh-connections/ssh-read/index.tsx
  src/api/ssh-connections/ssh-register/index.tsx
  src/components/dashboard/button/saveButton/index.tsx
  src/components/dashboard/cards/sshConnection-card/index.tsx
  src/components/dashboard/modals/sshConnection/index.tsx
  src/components/dashboard/modals/types/index.tsx
  src/pages/ssh-connection/index.tsx
Labels: enhancement

#64 Feature(HK-143): SSH 커넥션 수정 API
  src/api/ssh-connections/ssh-read/index.tsx
  src/api/ssh-connections/ssh-update/index.tsx
  src/components/dashboard/cards/sshConnection-card/index.tsx
  src/components/dashboard/modals/sshConnection/handlers/index.tsx
  src/components/dashboard/modals/sshConnection/index.tsx
  src/components/dashboard/modals/types/index.tsx
Labels: enhancement, fix

#65 Refactor(HK-156): 코드 리팩토링
  public/index.html
  src/App.tsx
  src/assets/SSH.gif
  src/assets/github-mark-white.png
  src/assets/google-mark.png
  src/assets/google_mark-si.png
  src/components/dashboard/button/index.style.tsx
  src/components/dashboard/button/saveButton/index.style.tsx
  src/components/dashboard/cards/keychain-card/index.style.tsx
  src/components/dashboard/cards/keychain-card/index.tsx
  src/components/dashboard/layout/dashboard-header/index.style.tsx
  src/components/dashboard/layout/dashboard-sidebar/index.style.tsx
  src/components/dashboard/modals/keychain-read-modal/handlers/index.tsx
  src/components/dashboard/modals/keychain-read-modal/index.style.tsx
  src/components/dashboard/modals/keychain-read-modal/inputGroup/index.tsx
  src/components/dashboard/modals/register-modal/index.style.tsx
  src/components/dashboard/modals/register-modal/index.tsx
  src/components/dashboard/modals/types/index.tsx
  src/components/header/index.style.tsx
  src/components/terminal/index.tsx
  src/pages/keychain/index.tsx
  src/pages/main/content/index.style.tsx
  src/pages/main/content/index.tsx
  src/pages/sign-in/content/index.style.tsx
  src/pages/sign-in/content/index.tsx
  src/pages/sign-in/sign-in-email/content/index.style.tsx
  src/pages/sign-in/sign-in-email/content/index.tsx
  src/pages/ssh-connection/test-page/index.tsx
  src/pages/terminal/index.style.tsx
  src/styles/global/GlobalStyle.tsx
Labels: enhancement, fix
