Repository team-dopamine/husk-web, pull requests merged in 2025-03, with the labels that each got.

#41 Feature(HK-118): Dashboard 페이지 UI 컴포넌트 구현
  package-lock.json
  package.json
  src/App.tsx
  src/assets/CloseIcon.svg
  src/components/dashboard/button/index.style.tsx
  src/components/dashboard/button/index.tsx
  src/components/dashboard/card/index.style.tsx
  src/components/dashboard/card/index.tsx
  src/components/dashboard/modal/index.style.tsx
  src/components/dashboard/modal/index.tsx
  src/pages/test/index.tsx
Labels: enhancement

#44 Feature(HK-133): 키체인 조회 API 구현 및 연동
  src/api/keychains/keychain-read/index.tsx
  src/api/keychains/keychain-register/index.tsx
  src/components/dashboard/button/index.tsx
  src/components/dashboard/keychain-read-modal/index.style.tsx
  src/components/dashboard/keychain-read-modal/index.tsx
  src/pages/test/index.tsx
Labels: enhancement

#45 Chore(HK-135): Nginx 설정에 따른 Dockerfile 및 CD 명령어 수정
  .github/workflows/cd.yml
  Dockerfile
Labels: documentation

#46 Fix(HK-135): 도커 실행 시 포트 매핑 수정
  .github/workflows/cd.yml
Labels: documentation, fix

#47 Feature(HK-128): 키체인 삭제 API 호출 구현
  src/api/keychains/keychain-delete/index.tsx
  src/components/dashboard/button/index.tsx
  src/components/dashboard/keychain-read-modal/index.tsx
  src/pages/test/index.tsx
Labels: enhancement, ssh connection

#49 Feature(HK-138): 로그인 상태에 따른 시작하기 버튼 라우팅
  src/pages/main/content/index.tsx
Labels: enhancement

#50 Feature(HK-125): 키체인 수정 API 연동 및 수정 모달창 구현
  package-lock.json
  package.json
  src/api/keychains/keychain-update/index.tsx
  src/components/dashboard/button/index.tsx
  src/components/dashboard/button/saveButton/index.style.tsx
  src/components/dashboard/button/saveButton/index.tsx
  src/components/dashboard/cards/keychain-card/index.style.tsx
  src/components/dashboard/cards/keychain-card/index.tsx
  src/components/dashboard/modals/keychain-read-modal/handlers/index.tsx
  src/components/dashboard/modals/keychain-read-modal/index.tsx
  src/components/dashboard/modals/keychain-read-modal/inputGroup/index.tsx
  src/components/dashboard/modals/keychain-read-modal/types/index.tsx
  src/components/dashboard/modals/register-modal/index.tsx
  src/components/dashboard/modals/register-modal/types/index.tsx
  src/hooks/useModal/index.tsx
  src/pages/keychain/index.tsx
Labels: enhancement, fix, keychain

#51 Feature(HK-127): 키체인 복호화 API 연동 및 복호화 기능 추가
  src/api/keychains/keychain-decrypt/index.tsx
  src/components/dashboard/button/index.style.tsx
  src/components/dashboard/button/index.tsx
  src/components/dashboard/cards/keychain-card/index.tsx
  src/components/dashboard/cards/register-card/index.style.tsx
  src/components/dashboard/modals/keychain-read-modal/index.style.tsx
  src/components/dashboard/modals/keychain-read-modal/index.tsx
  src/components/dashboard/modals/keychain-read-modal/inputGroup/index.tsx
  src/components/dashboard/modals/keychain-read-modal/types/index.tsx
  src/pages/keychain/index.tsx
Labels: enhancement, fix, keychain
