Repository team-dopamine/husk-web, pull requests merged in 2025-01, with the labels that each got.

#12 Fix(HK-65): 절대경로 오류 수정
  craco.config.js
  package-lock.json
  package.json
  src/pages/main/index.tsx
  src/pages/sign-in/index.tsx
  tsconfig.json
Labels: bug, enhancement

#13 Feature(HK-70): 일반 회원가입 이메일 인증 페이지 구현
  src/App.tsx
  src/components/sign-up/email-verify/index.style.tsx
  src/components/sign-up/email-verify/index.tsx
  src/components/sign-up/index.style.tsx
  src/components/sign-up/index.tsx
  src/pages/sign-up/content/index.style.tsx
  src/pages/sign-up/content/index.tsx
  src/pages/sign-up/index.style.tsx
  src/pages/sign-up/index.tsx
Labels: enhancement, authorization

#14 Feature(HK-81): 일반 회원가입 비밀번호 설정 페이지 구현
  src/App.tsx
  src/components/sign-up/password-setting/index.style.tsx
  src/components/sign-up/password-setting/index.tsx
  src/pages/sign-up/password/index.style.tsx
  src/pages/sign-up/password/index.tsx
  src/pages/sign-up/password/password-content/index.style.tsx
  src/pages/sign-up/password/password-content/index.tsx
Labels: enhancement, authorization

#15 Feature (HK-78): Deploy 파이프라인 수정
  .github/workflows/cd.yml
  Dockerfile
Labels: enhancement

#16 Fix(HK-78): deploy workflow의 trigger 브랜치와 ssh 접속 방식 수정
  .github/workflows/cd.yml
Labels: bug

#20 Feature(HK-71): API 초기 설정
  .gitignore
  package-lock.json
  package.json
  src/api/axios.tsx
Labels: enhancement

#21 Feature(HK-86): 인증코드 전송 API 연결
  src/api/send-code/index.tsx
  src/components/sign-up/email-verify/index.tsx
  src/components/sign-up/index.style.tsx
  src/components/sign-up/index.tsx
  src/pages/sign-up/content/index.tsx
Labels: enhancement

#22 Feature(HK-88): 인증코드 검증 API 연결
  src/api/verify-code/index.tsx
  src/components/sign-up/email-verify/index.tsx
  src/pages/sign-up/content/index.tsx
Labels: enhancement, authorization

#24 Feature(HK-94): 서비스 사용자 이용 약관 조회 API 연동
  src/api/read-terms/index.tsx
  src/pages/sign-in/content/index.tsx
  src/pages/sign-up/read-terms/read-terms-content/index.style.tsx
  src/pages/sign-up/read-terms/read-terms-content/index.tsx
Labels: enhancement, authorization

#23 Feature(HK-91): 회원가입 API 연결
  src/api/sign-up/index.tsx
  src/components/sign-up/email-verify/index.tsx
  src/components/sign-up/password-setting/index.tsx
  src/pages/sign-up/content/index.tsx
  src/pages/sign-up/password/password-content/index.tsx
Labels: enhancement, authorization
